image: python:3.9

stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/

before_script:
  - python -m pip install --upgrade pip
  - pip install coverage

build-job:
  stage: build
  script:
    - python --version
    - pip list

test-job:
  stage: test
  script:
    - python -m unittest unitTests.py -v
    - coverage run -m unittest unitTests.py
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

# Variables d'environnement sécurisées (à configurer dans GitLab CI/CD)
# CODECOV_TOKEN: [À définir dans Settings > CI/CD > Variables]