language: python
python:
  - "3.7"  
  - "3.9"

before_install:
  - python -m pip install --upgrade pip
  - pip install -U pip
  - pip freeze > requirements.txt  
  - python --version
  - pip install codecov
  
install:
  - pip install -r requirements.txt --use-feature=2020-resolver

script:
 - coverage run unitTests.py
 
after_success:
 - codecov