language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install coverage

script:
  - python -m unittest unitTests.py -v
  - coverage run -m unittest unitTests.py
  - coverage report -m

# Variables d'environnement sécurisées (à configurer manuellement sur Travis)
# CODECOV_TOKEN: [À définir dans les paramètres Travis]

cache: pip